language: ruby
rvm:
  - &ruby 2.4
cache: bundler
script: script/cibuild
env:
  matrix:
    - JEKYLL_VERSION="~> 3.0"
    - JEKYLL_VERSION=">= 4.0.0.pre.alpha1"
matrix:
  include:
    - rvm: *ruby
      name: "Profile Memory Usage"
      script: bundle exec ruby script/memprof
    - rvm: *ruby
      name: "Benchmark Default Host"
      script: script/cibench
    - rvm: *ruby
      env: PAGES_AVATARS_URL="http://avatars.example.com"
      name: "Benchmark Custom Host"
      script: script/cibench
